### ISSUE TITLE
PETDANCE needs co-maint on three modules

### ISSUE THREAD

**Issue by petdance** [Perl-Critic/Perl-Critic#766]
http://search.cpan.org/~petdance/Perl-Critic/ shows that three modules are not maintained by me, so my 1.127_01 upload is unauthorized.

@thaljef Can you do this please?

- Perl::Critic::Policy::BuiltinFunctions::ProhibitUselessTopic
- Perl::Critic::Policy::ControlStructures::ProhibitYadaOperator
- Perl::Critic::Policy::RegularExpressions::ProhibitUselessTopic

**Comment by thaljef** [comment]
Try again now. I have assigned first-come rights on those packages to CRITICRE. I don't know if that will actually solve the problem, but at least now they will match all the other packages.

**Comment by thaljef** [comment]
Presumably, you can just re-index rather than having to upload a new tarball.

**Comment by petdance** [comment]
What is CRITICRE?  Is it some sort of group of which I'm a member?

I've tried the reindex and am now waiting for PAUSE to do its thing.

**Comment by thaljef** [comment]
Yes, CRITICRE is some kind of magical group thing on PAUSE. You appear to be a member. But I have no idea how someone actually joins. That's probably a question for @andk.

**Comment by petdance** [comment]
What is the RE in CRITICRE?

**Comment by petdance** [comment]
It's still showing as unauthorized so I'm going to do a _02 release.

**Comment by petdance** [comment]
It's still showing as unauthorized so I'm going to do a _02 release.

**Comment by thaljef** [comment]
> What is the RE in CRITICRE?

I think it means "Release Engineer".

**Comment by petdance** [comment]
No luck, it still shows as being unauthorized.  http://search.cpan.org/~petdance/Perl-Critic-1.127_02/

**Comment by petdance** [comment]
I talked to RJBS about this, and he said that the CRITICRE and other mailing list accounts have a note: "There's currently no way to edit the table except direct SQL. The table says who is representative of a mailing list", and then opined "Andreas alone, I guess, can do that."  So I'm going to mail him and cc @thaljef

**Comment by petdance** [comment]
@thaljef Since we don't know when Andreas can get to adding me to CRITICRE, can you please add PETDANCE as comaint on these three:

* Perl::Critic::Policy::BuiltinFunctions::ProhibitUselessTopic
* Perl::Critic::Policy::ControlStructures::ProhibitYadaOperator
* Perl::Critic::Policy::RegularExpressions::ProhibitUselessTopic

That way I can make an actual release.

**Comment by andk** [comment]
Danger, Will Robinson! There are a couple of things to clarify to
determine the right way forward. Please let me know what you actually
want to achieve.

(1) CRITICRE is effectively ownership. Each of the users in this group
can change permissions on all packages the group owns. That's not
something you share lightly.

(2) By giving first-come to CRITICRE @thaljef did not change the rights
of @petdance. He only enabled the other members of CRITICRE to pass comaint
to @petdance.

(3) @thaljef said "You appear to be a member". I cannot confirm.
https://pause.perl.org/pause/authenquery?ACTION=show_ml_repr is the
place where to look and PETDANCE is not listed as part of CRITICRE.

(4) It has already been said: New uploads are never needed to debug
permission problems. If permissions have changed, a reindex will
reconsider permissions and you can repeat the process as often as you
need until the permissions seem right.

(5) But dev releases are never indexed. 1.127_01 and 1.127_02 are dev
releases. You are not testing the PAUSE indexer with dev releases

(6) What @petdance needs as a minimum now to make a fully successful
release, is comaintainership. If that's what is intended, I'm not
needed.

(7) If you still need my help, please make your intent as clear as
possible. I do not feel competent enough to second-guess what is
intended.

Thanks, and sorry that it is so complicated.

**Comment by petdance** [comment]
> (1) CRITICRE is effectively ownership. Each of the users in this group can change permissions on all packages the group owns. That's not something you share lightly.

Yes, understood.  Jeff has handed off the entire project.

> (2) By giving first-come to CRITICRE @thaljef did not change the rights of @petdance. He only enabled the other members of CRITICRE to pass comaint to @petdance.

Understood.  He thought that I was already in CRITICRE when he made that change.

> (5) But dev releases are never indexed. 1.127_01 and 1.127_02 are dev releases. You are not testing the PAUSE indexer with dev releases

I'm not clear on the relationship (if any) between the PAUSE indexer and how things show up on search.cpan.org.

http://search.cpan.org/~petdance/Perl-Critic-1.127_02/ shows "** UNAUTHORIZED RELEASE **"  and I'm assuming it will do the same when I release 1.128 as well.

**Comment by petdance** [comment]
Can one of @thaljef or @andk please assign comaint on these three modules so I can release?

-     Perl::Critic::Policy::BuiltinFunctions::ProhibitUselessTopic
-     Perl::Critic::Policy::ControlStructures::ProhibitYadaOperator
-     Perl::Critic::Policy::RegularExpressions::ProhibitUselessTopic

Thank you.

**Comment by andk** [comment]
Done.

While we are at it, may I ask about the role of CRITICRE? Is there a reason to have this organizational unit? Why not simply transfer first-come to PETDANCE?

I'm only asking, not suggesting anything. But if admin power is needed even though there are people in the group CRITICRE, then what is it good for? Would passing first-come to Andy Lester be an option?

Thanks!

**Comment by petdance** [comment]
Thanks for adding me as comaint.  I reindexed and [search.cpan.org is happy](http://search.cpan.org/~petdance/Perl-Critic-1.127_02/), although [metacpan still shows as unauthorized](https://metacpan.org/release/PETDANCE/Perl-Critic-1.127_02).  Perhaps that will clear up in a bit.

I don't know about the intent of CRITICRE, as I just learned about it recently.  I guess that what you're saying is that anyone else who is in CRITICRE could have taken care of giving me comaint.  If I'd thought of that, I'd have pinged one of the CRITICRE people.  Is there a way we can see who is in CRITICRE?

**Comment by thaljef** [comment]
Once upon a time, @clonezone and I were both active maintainers of various Perl-Critic distributions. I wanted a way for both of us (and potentially others) to make releases without having to worry about passing co-maint to each person for each new package.

So the solution we worked out with @andk was CRITICRE. As I understood it, giving first-come rights to CRITICRE would effectively give co-maint to every member. That way, someone releasing Perl-Critic could pass permissions for new packages just once, instead passing them individually to every present or future developer.

Does that make sense?

**Comment by andk** [comment]
>>>>> On Fri, 26 May 2017 12:14:48 -0700, Jeffrey Ryan Thalhammer <notifications@github.com> said:

  > Once upon a time, @clonezone and I were both active maintainers of
  > various Perl-Critic distributions. I wanted a way for both of us (and
  > potentially others) to make releases without having to worry about
  > passing co-maint to each person for each new package.

  > So the solution we worked out with @andk was CRITICRE. As I understood
  > it, giving first-come rights to CRITICRE would effectively give
  > co-maint to every member. That way, someone releasing Perl-Critic
  > could pass permissions for new packages just once, instead passing
  > them individually to every present or future developer.

  > Does that make sense?

Well, you seem to have missed at least one point. Giving first-come to
CRITICRE gives all members of CRITICRE *all* rights except for one: they
cannot kick other members out of CRITICRE. But they can give away
firstcome and comaint rights to any module belonging to CRITICRE. It is
comparable to collective ownership. Often this is a good model of
ownership but I fear it is underdocumented, does not work as you think
and requires a lot of trust.

But one year ago PAUSE got new code that does what you describe above:
comaint permissions now propagate to the peers when a new module is
added to a distro and the distro is uploaded/indexed. This redundantizes
the need for group ownership as far as I can see.

-- 
andreas

**Comment by andk** [comment]
>>>>> On Fri, 26 May 2017 07:38:36 -0700, Andy Lester <notifications@github.com> said:

  > Is there a way we can see who is in CRITICRE?

https://pause.perl.org/pause/authenquery?ACTION=show_ml_repr

-- 
andreas

**Comment by petdance** [comment]
> https://pause.perl.org/pause/authenquery?ACTION=show_ml_repr

That's weird.  I'm in a TKML list with SREZIC.  I can't imagine why.

**Comment by andk** [comment]
>>>>> On Sat, 27 May 2017 12:24:36 -0700, Andy Lester <notifications@github.com> said:

  >     https://pause.perl.org/pause/authenquery?ACTION=show_ml_repr
  > That's weird. I'm in a TKML list with SREZIC. I can't imagine why.

OK, I've removed it:

mysql> delete from list2user where maillistid ='TKML' and userid='PETDANCE';
Query OK, 1 row affected (0.14 sec)



-- 
andreas
